export const supportedLanguages: Record<string, string> = {
  Afrikaans: "af",
  Albanian: "sq",
  Amharic: "am",
  Arabic: "ar",
  Armenian: "hy",
  Assamese: "as",
  Aymara: "ay",
  Azerbaijani: "az",
  Bambara: "bm",
  Basque: "eu",
  Belarusian: "be",
  Bengali: "bn",
  Bhojpuri: "bho",
  Bosnian: "bs",
  Bulgarian: "bg",
  Catalan: "ca",
  Cebuano: "ceb",
  Chichewa: "ny",
  "Chinese (Simplified)": "zh-CN",
  "Chinese (Traditional)": "zh-TW",
  Corsican: "co",
  Croatian: "hr",
  Czech: "cs",
  Danish: "da",
  Dhivehi: "dv",
  Dogri: "doi",
  Dutch: "nl",
  English: "en",
  Esperanto: "eo",
  Estonian: "et",
  Ewe: "ee",
  Filipino: "tl",
  Finnish: "fi",
  French: "fr",
  Frisian: "fy",
  Galician: "gl",
  Georgian: "ka",
  German: "de",
  Greek: "el",
  Guarani: "gn",
  Gujarati: "gu",
  "Haitian Creole": "ht",
  Hausa: "ha",
  Hawaiian: "haw",
  Hebrew: "iw",
  Hindi: "hi",
  Hmong: "hmn",
  Hungarian: "hu",
  Icelandic: "is",
  Igbo: "ig",
  Ilocano: "ilo",
  Indonesian: "id",
  Irish: "ga",
  Italian: "it",
  Japanese: "ja",
  Javanese: "jw",
  Kannada: "kn",
  Kazakh: "kk",
  Khmer: "km",
  Kinyarwanda: "rw",
  Konkani: "gom",
  Korean: "ko",
  Krio: "kri",
  "Kurdish (Kurmanji)": "ku",
  "Kurdish (Sorani)": "ckb",
  Kyrgyz: "ky",
  Lao: "lo",
  Latin: "la",
  Latvian: "lv",
  Lingala: "ln",
  Lithuanian: "lt",
  Luganda: "lg",
  Luxembourgish: "lb",
  Macedonian: "mk",
  Maithili: "mai",
  Malagasy: "mg",
  Malay: "ms",
  Malayalam: "ml",
  Maltese: "mt",
  Maori: "mi",
  Marathi: "mr",
  "Meiteilon (Manipuri)": "mni-Mtei",
  Mizo: "lus",
  Mongolian: "mn",
  "Myanmar (Burmese)": "my",
  Nepali: "ne",
  Norwegian: "no",
  "Odia (Oriya)": "or",
  Oromo: "om",
  Pashto: "ps",
  Persian: "fa",
  Polish: "pl",
  Portuguese: "pt",
  Punjabi: "pa",
  Quechua: "qu",
  Romanian: "ro",
  Russian: "ru",
  Samoan: "sm",
  Sanskrit: "sa",
  "Scots Gaelic": "gd",
  Sepedi: "nso",
  Serbian: "sr",
  Sesotho: "st",
  Shona: "sn",
  Sindhi: "sd",
  Sinhala: "si",
  Slovak: "sk",
  Slovenian: "sl",
  Somali: "so",
  Spanish: "es",
  Sundanese: "su",
  Swahili: "sw",
  Swedish: "sv",
  Tajik: "tg",
  Tamil: "ta",
  Tatar: "tt",
  Telugu: "te",
  Thai: "th",
  Tigrinya: "ti",
  Tsonga: "ts",
  Turkish: "tr",
  Turkmen: "tk",
  Twi: "ak",
  Ukrainian: "uk",
  Urdu: "ur",
  Uyghur: "ug",
  Uzbek: "uz",
  Vietnamese: "vi",
  Welsh: "cy",
  Xhosa: "xh",
  Yiddish: "yi",
  Yoruba: "yo",
  Zulu: "zu",
};

export const commonLanguages = Object.keys(supportedLanguages);

/**
 * Maps each English language key (as stored in the DB) to the language name
 * written in its own native script. Used to display language options to end
 * users in the language they actually recognise.
 */
export const nativeLanguageNames: Record<string, string> = {
  Afrikaans: "Afrikaans",
  Albanian: "Shqip",
  Amharic: "አማርኛ",
  Arabic: "العربية",
  Armenian: "Հայերեն",
  Assamese: "অসমীয়া",
  Aymara: "Aymar aru",
  Azerbaijani: "Azərbaycan",
  Bambara: "Bamanankan",
  Basque: "Euskara",
  Belarusian: "Беларуская",
  Bengali: "বাংলা",
  Bhojpuri: "भोजपुरी",
  Bosnian: "Bosanski",
  Bulgarian: "Български",
  Catalan: "Català",
  Cebuano: "Cebuano",
  Chichewa: "Chichewa",
  "Chinese (Simplified)": "中文（简体）",
  "Chinese (Traditional)": "中文（繁體）",
  Corsican: "Corsu",
  Croatian: "Hrvatski",
  Czech: "Čeština",
  Danish: "Dansk",
  Dhivehi: "ދިވެހި",
  Dogri: "डोगरी",
  Dutch: "Nederlands",
  English: "English",
  Esperanto: "Esperanto",
  Estonian: "Eesti",
  Ewe: "Eʋegbe",
  Filipino: "Filipino",
  Finnish: "Suomi",
  French: "Français",
  Frisian: "Frysk",
  Galician: "Galego",
  Georgian: "ქართული",
  German: "Deutsch",
  Greek: "Ελληνικά",
  Guarani: "Avañeʼẽ",
  Gujarati: "ગુજરાતી",
  "Haitian Creole": "Kreyòl ayisyen",
  Hausa: "Hausa",
  Hawaiian: "ʻŌlelo Hawaiʻi",
  Hebrew: "עברית",
  Hindi: "हिंदी",
  Hmong: "Hmoob",
  Hungarian: "Magyar",
  Icelandic: "Íslenska",
  Igbo: "Asụsụ Igbo",
  Ilocano: "Ilokano",
  Indonesian: "Bahasa Indonesia",
  Irish: "Gaeilge",
  Italian: "Italiano",
  Japanese: "日本語",
  Javanese: "Basa Jawa",
  Kannada: "ಕನ್ನಡ",
  Kazakh: "Қазақ тілі",
  Khmer: "ភាសាខ្មែរ",
  Kinyarwanda: "Ikinyarwanda",
  Konkani: "कोंकणी",
  Korean: "한국어",
  Krio: "Krio",
  "Kurdish (Kurmanji)": "Kurdî (Kurmancî)",
  "Kurdish (Sorani)": "کوردی (سۆرانی)",
  Kyrgyz: "Кыргызча",
  Lao: "ລາວ",
  Latin: "Latina",
  Latvian: "Latviešu",
  Lingala: "Lingála",
  Lithuanian: "Lietuvių",
  Luganda: "Luganda",
  Luxembourgish: "Lëtzebuergesch",
  Macedonian: "Македонски",
  Maithili: "मैथिली",
  Malagasy: "Malagasy",
  Malay: "Bahasa Melayu",
  Malayalam: "മലയാളം",
  Maltese: "Malti",
  Maori: "Te Reo Māori",
  Marathi: "मराठी",
  "Meiteilon (Manipuri)": "মেইতেই লোন্",
  Mizo: "Mizo ṭawng",
  Mongolian: "Монгол",
  "Myanmar (Burmese)": "မြန်မာဘာသာ",
  Nepali: "नेपाली",
  Norwegian: "Norsk",
  "Odia (Oriya)": "ଓଡ଼ିଆ",
  Oromo: "Afaan Oromoo",
  Pashto: "پښتو",
  Persian: "فارسی",
  Polish: "Polski",
  Portuguese: "Português",
  Punjabi: "ਪੰਜਾਬੀ",
  Quechua: "Runasimi",
  Romanian: "Română",
  Russian: "Русский",
  Samoan: "Gagana Samoa",
  Sanskrit: "संस्कृतम्",
  "Scots Gaelic": "Gàidhlig",
  Sepedi: "Sepedi",
  Serbian: "Српски",
  Sesotho: "Sesotho",
  Shona: "ChiShona",
  Sindhi: "سنڌي",
  Sinhala: "සිංහල",
  Slovak: "Slovenčina",
  Slovenian: "Slovenščina",
  Somali: "Soomaali",
  Spanish: "Español",
  Sundanese: "Basa Sunda",
  Swahili: "Kiswahili",
  Swedish: "Svenska",
  Tajik: "Тоҷикӣ",
  Tamil: "தமிழ்",
  Tatar: "Татарча",
  Telugu: "తెలుగు",
  Thai: "ภาษาไทย",
  Tigrinya: "ትግርኛ",
  Tsonga: "Xitsonga",
  Turkish: "Türkçe",
  Turkmen: "Türkmen",
  Twi: "Twi",
  Ukrainian: "Українська",
  Urdu: "اردو",
  Uyghur: "ئۇيغۇرچە",
  Uzbek: "O'zbek",
  Vietnamese: "Tiếng Việt",
  Welsh: "Cymraeg",
  Xhosa: "isiXhosa",
  Yiddish: "ייִדיש",
  Yoruba: "Yorùbá",
  Zulu: "isiZulu",
};
