export const defaultButtonLabel = "Send";

export enum InputBlockType {
  TEXT = "text input",
  NUMBER = "number input",
  EMAIL = "email input",
  URL = "url input",
  DATE = "date input",
  TIME = "time input",
  PHONE = "phone number input",
  CHOICE = "choice input",
  PICTURE_CHOICE = "picture choice input",
  PAYMENT = "payment input",
  RATING = "rating input",
  FILE = "file input",
  CARDS = "cards",
  CTA_URL = "cta url button",
  LOCATION_REQUEST = "location request",
  ADDRESS = "address input",
  TEMPLATE = "template message",
  FLOW = "whatsapp flow",
  MEDIA_CAROUSEL = "media carousel",
  PRODUCT_CAROUSEL = "product carousel",
  INTERACTIVE_LIST = "interactive list",
}

export const replyEventInputTypeFromEnum = {
  [InputBlockType.TEXT]: "text",
  [InputBlockType.NUMBER]: "number",
  [InputBlockType.EMAIL]: "email",
  [InputBlockType.URL]: "url",
  [InputBlockType.DATE]: "date",
  [InputBlockType.TIME]: "time",
  [InputBlockType.PHONE]: "phone",
  [InputBlockType.CHOICE]: "buttons",
  [InputBlockType.PICTURE_CHOICE]: "picture choice",
  [InputBlockType.PAYMENT]: "payment",
  [InputBlockType.RATING]: "rating",
  [InputBlockType.FILE]: "file",
  [InputBlockType.CARDS]: "cards",
  [InputBlockType.CTA_URL]: "cta url",
  [InputBlockType.LOCATION_REQUEST]: "location",
  [InputBlockType.ADDRESS]: "address",
  [InputBlockType.TEMPLATE]: "template",
  [InputBlockType.FLOW]: "flow",
  [InputBlockType.MEDIA_CAROUSEL]: "media carousel",
  [InputBlockType.PRODUCT_CAROUSEL]: "product carousel",
  [InputBlockType.INTERACTIVE_LIST]: "whatsapp list",
};
